// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {gh} from '../models';

export function ChooseSoundFile():Promise<string>;

export function CollapseWindow():Promise<void>;

export function ConfirmAll():Promise<void>;

export function ConfirmNotification(arg1:string):Promise<void>;

export function ExpandToast():Promise<void>;

export function ExpandWindow(arg1:number):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetNotifications():Promise<Array<gh.Notification>>;

export function GetUnconfirmedCount():Promise<number>;

export function GetVersion():Promise<string>;

export function GetWindowPosition():Promise<number|number>;

export function GetWindowSize():Promise<number|number>;

export function OpenAndCollapse(arg1:string,arg2:string):Promise<void>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function ResetWindowPosition():Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:number,arg4:Array<string>,arg5:number,arg6:number,arg7:number,arg8:number,arg9:boolean,arg10:string,arg11:number,arg12:boolean,arg13:boolean,arg14:number,arg15:number,arg16:string,arg17:string):Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;
