// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {gh} from '../models';

export function ChooseSoundFile():Promise<string>;

export function CollapseWindow():Promise<void>;

export function ConfirmAll():Promise<void>;

export function ConfirmNotification(arg1:string):Promise<void>;

export function ExpandToast():Promise<void>;

export function ExpandWindow(arg1:number):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetNotifications():Promise<Array<gh.Notification>>;

export function GetUnconfirmedCount():Promise<number>;

export function GetWindowPosition():Promise<number|number>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function SaveConfig(arg1:string,arg2:string,arg3:number,arg4:Array<string>,arg5:number,arg6:number,arg7:boolean,arg8:string,arg9:number,arg10:boolean,arg11:boolean,arg12:number,arg13:number,arg14:string,arg15:string):Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number):Promise<void>;
