// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseSoundFile() {
  return window['go']['main']['App']['ChooseSoundFile']();
}

export function CollapseWindow() {
  return window['go']['main']['App']['CollapseWindow']();
}

export function ConfirmAll() {
  return window['go']['main']['App']['ConfirmAll']();
}

export function ConfirmNotification(arg1) {
  return window['go']['main']['App']['ConfirmNotification'](arg1);
}

export function ExpandToast() {
  return window['go']['main']['App']['ExpandToast']();
}

export function ExpandWindow(arg1) {
  return window['go']['main']['App']['ExpandWindow'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetUnconfirmedCount() {
  return window['go']['main']['App']['GetUnconfirmedCount']();
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function SaveConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function SaveWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowPosition'](arg1, arg2);
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}
